name: Quick Test

on:
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  quick-test:
    name: Quick Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install basic dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
    
    - name: Validate Python syntax
      run: |
        python -m py_compile pipelines/*.py
        python -m py_compile pipelines/config/*.py
        python -m py_compile pipelines/utils/*.py
        python -m py_compile monitoring/*.py
    
    - name: Validate YAML configuration
      run: |
        python -c "
import yaml
with open('pipelines/config/config.yaml', 'r') as f:
    config = yaml.safe_load(f)
print('✓ Configuration YAML is valid')
"
    
    - name: Check SQL files exist
      run: |
        test -f scripts/init_database.sql
        test -f scripts/bronze/ddl_bronze.sql
        test -f scripts/silver/ddl_silver.sql
        test -f scripts/gold/ddl_gold.sql
        echo "✓ All SQL files present"
    
    - name: Validate README
      run: |
        if [ -s README.md ]; then
          echo "✓ README.md exists and is not empty"
        else
          echo "✗ README.md is missing or empty"
          exit 1
        fi